###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "adel",
  "age": 1000,
  "email": "10002@asdasd.com"
}


### 
GET http://localhost:3000/api/users HTTP/1.1

###

GET http://localhost:3000/api/users/64417ac6254a5e4e7d47bb04 HTTP/1.1


###
PUT http://localhost:3000/api/users/64417ac6254a5e4e7d47bb04 HTTP/1.1
Content-Type: application/json

{
  "name": "chapalapachala",
  "age": 30,
  "email": "zhape@asd.com"
}

###
DELETE http://localhost:3000/api/users/64417ac6254a5e4e7d47bb04 HTTP/1.1


